export enum AuditEventEnum {
  // USER
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_DEACTIVATED_BY_ADMIN = 'USER_DEACTIVATED_BY_ADMIN',
  USER_REACTIVATED = 'USER_REACTIVATED',
  USER_SESSIONS_REVOKED = 'USER_SESSIONS_REVOKED',
  USER_ROLE_ASSIGNED = 'USER_ROLE_ASSIGNED',
  USER_ROLE_REVOKED = 'USER_ROLE_REVOKED',
  USER_UNLOCKED = 'USER_UNLOCKED',
  USER_AUTO_FLAGGED = 'USER_AUTO_FLAGGED',

  // AUTH
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  OTP_VERIFIED = 'OTP_VERIFIED',

  // DISCREET MODE
  DISCREET_MODE_ENABLED = 'DISCREET_MODE_ENABLED',
  DISCREET_MODE_DISABLED = 'DISCREET_MODE_DISABLED',
  DISCREET_MODE_PASSCODE_CHANGED = 'DISCREET_MODE_PASSCODE_CHANGED',

  // ADMIN ONBOARDING / REGISTRATION
  ADMIN_REGISTERED = 'ADMIN_REGISTERED',
  ADMIN_REGISTRATION_RESENT = 'ADMIN_REGISTRATION_RESENT',
  ADMIN_REGISTRATION_CANCELLED = 'ADMIN_REGISTRATION_CANCELLED',
  ADMIN_EMAIL_CHANGE_INITIATED = 'ADMIN_EMAIL_CHANGE_INITIATED',
  ADMIN_EMAIL_CHANGE_VERIFIED = 'ADMIN_EMAIL_CHANGE_VERIFIED',

  // USER PROMOTION
  USER_PROMOTION_INITIATED = 'USER_PROMOTION_INITIATED',
  USER_PROMOTION_RESENT = 'USER_PROMOTION_RESENT',

  // REPORT
  REPORT_CREATED = 'REPORT_CREATED',
  REPORT_UPDATED = 'REPORT_UPDATED',
  REPORT_OPENED = 'REPORT_OPENED',
  REPORT_MEDIA_DOWNLOADED = 'REPORT_MEDIA_DOWNLOADED',
  REPORTER_INFORMATION_OPENED = 'REPORTER_INFORMATION_OPENED',
  REPORT_STATUS_CHANGED = 'REPORT_STATUS_CHANGED',
  REPORT_MORE_INFORMATION_REQUESTED = 'REPORT_MORE_INFORMATION_REQUESTED',
  REPORT_INFORMATION_RESPONDED = 'REPORT_INFORMATION_RESPONDED',
  REPORT_ASSIGNED = 'REPORT_ASSIGNED',
  REPORT_UNASSIGNED = 'REPORT_UNASSIGNED',
  REPORT_ESCALATED = 'REPORT_ESCALATED',
  REPORT_CLOSED = 'REPORT_CLOSED',
  REPORT_REJECTED = 'REPORT_REJECTED',
  REPORT_WITHDRAWN = 'REPORT_WITHDRAWN',

  // POST
  POST_CREATED = 'POST_CREATED',
  POST_UPDATED = 'POST_UPDATED',
  POST_APPROVED = 'POST_APPROVED',
  POST_REJECTED = 'POST_REJECTED',
  POST_PUBLISHED = 'POST_PUBLISHED',
  POST_UNPUBLISHED = 'POST_UNPUBLISHED',
  POST_DELETED = 'POST_DELETED',

  // MISSING PERSON
  MISSING_PERSON_CREATED = 'MISSING_PERSON_CREATED',
  MISSING_PERSON_UPDATED = 'MISSING_PERSON_UPDATED',
  MISSING_PERSON_APPROVED = 'MISSING_PERSON_APPROVED',
  MISSING_PERSON_REJECTED = 'MISSING_PERSON_REJECTED',
  MISSING_PERSON_FOUND = 'MISSING_PERSON_FOUND',
  MISSING_PERSON_MORE_INFO_REQUESTED = 'MISSING_PERSON_MORE_INFO_REQUESTED',
  MISSING_PERSON_REDACTED = 'MISSING_PERSON_REDACTED',
  MISSING_PERSON_REWARD_REVIEWED = 'MISSING_PERSON_REWARD_REVIEWED',
  MISSING_PERSON_DELETED = 'MISSING_PERSON_DELETED',
  MISSING_PERSON_MEDIA_DOWNLOADED = 'MISSING_PERSON_MEDIA_DOWNLOADED',

  // INFORMATION SUBMISSION
  INFORMATION_SUBMITTED = 'INFORMATION_SUBMITTED',
  INFORMATION_UNDER_REVIEW = 'INFORMATION_UNDER_REVIEW',
  INFORMATION_REVIEWED = 'INFORMATION_REVIEWED',
  INFORMATION_REJECTED = 'INFORMATION_REJECTED',
  INFORMATION_SUBMISSION_UPDATED = 'INFORMATION_SUBMISSION_UPDATED',
  INFORMATION_SUBMISSION_DELETED = 'INFORMATION_SUBMISSION_DELETED',
  INFORMATION_SUBMISSION_MEDIA_DOWNLOADED = 'INFORMATION_SUBMISSION_MEDIA_DOWNLOADED',

  // VICTIM PROFILE
  VICTIM_PROFILE_CREATED = 'VICTIM_PROFILE_CREATED',
  VICTIM_PROFILE_UPDATED = 'VICTIM_PROFILE_UPDATED',
  VICTIM_PROFILE_VERIFIED = 'VICTIM_PROFILE_VERIFIED',
  VICTIM_PROFILE_CONSENT_RECORDED = 'VICTIM_PROFILE_CONSENT_RECORDED',
  VICTIM_PROFILE_PRIVACY_REVIEWED = 'VICTIM_PROFILE_PRIVACY_REVIEWED',
  VICTIM_PROFILE_APPROVED = 'VICTIM_PROFILE_APPROVED',
  VICTIM_PROFILE_PUBLISHED = 'VICTIM_PROFILE_PUBLISHED',
  VICTIM_PROFILE_REJECTED = 'VICTIM_PROFILE_REJECTED',
  VICTIM_PROFILE_CLAIMED = 'VICTIM_PROFILE_CLAIMED',
  VICTIM_PROFILE_UNCLAIMED = 'VICTIM_PROFILE_UNCLAIMED',
  VICTIM_PROFILE_MEDIA_DOWNLOADED = 'VICTIM_PROFILE_MEDIA_DOWNLOADED',
  VICTIM_PROFILE_DELETED = 'VICTIM_PROFILE_DELETED',
  VICTIM_PROFILE_UNPUBLISHED = 'VICTIM_PROFILE_UNPUBLISHED',
  VICTIM_PROFILE_GATES_UPDATED = 'VICTIM_PROFILE_GATES_UPDATED',
  VICTIM_PROFILE_CHILD_SAFETY_FIRST_CONFIRMED = 'VICTIM_PROFILE_CHILD_SAFETY_FIRST_CONFIRMED',
  VICTIM_PROFILE_CHILD_SAFETY_REVIEWED = 'VICTIM_PROFILE_CHILD_SAFETY_REVIEWED',
  VICTIM_PROFILE_CHILD_SAFETY_REVIEW_REVERSED = 'VICTIM_PROFILE_CHILD_SAFETY_REVIEW_REVERSED',
  VICTIM_PROFILE_CONSENT_REVOKED = 'VICTIM_PROFILE_CONSENT_REVOKED',
  VICTIM_PROFILE_BANK_DETAILS_UPDATED = 'VICTIM_PROFILE_BANK_DETAILS_UPDATED',
  VICTIM_PROFILE_RESUBMITTED = 'VICTIM_PROFILE_RESUBMITTED',
  // Logged when reconcileProfileTotal() auto-corrects a drifted cached total.
  VICTIM_PROFILE_TOTAL_RECONCILED = 'VICTIM_PROFILE_TOTAL_RECONCILED',

  // SUPPORT
  SUPPORT_CREATED = 'SUPPORT_CREATED',
  SUPPORT_UPDATED = 'SUPPORT_UPDATED',
  SUPPORT_CONFIRMED = 'SUPPORT_CONFIRMED',
  SUPPORT_COMPLETED = 'SUPPORT_COMPLETED',
  SUPPORT_CANCELLED = 'SUPPORT_CANCELLED',
  SUPPORT_FAILED = 'SUPPORT_FAILED',

  // ROLE
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_DELETED = 'ROLE_DELETED',
  ROLE_MEMBERS_VIEWED = 'ROLE_MEMBERS_VIEWED',

  // PERMISSION
  PERMISSION_ASSIGNED = 'PERMISSION_ASSIGNED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',
  PERMISSIONS_BULK_REVOKED = 'PERMISSIONS_BULK_REVOKED',
  PERMISSIONS_SET_REPLACED = 'PERMISSIONS_SET_REPLACED',

  // AUDIT LOG
  AUDIT_LOG_VIEWED = 'AUDIT_LOG_VIEWED',
  AUDIT_LOG_EXPORTED = 'AUDIT_LOG_EXPORTED',
  AUDIT_LOG_INTEGRITY_VERIFIED = 'AUDIT_LOG_INTEGRITY_VERIFIED',
  AUDIT_LOG_PURGE_PREVIEWED = 'AUDIT_LOG_PURGE_PREVIEWED',
  AUDIT_LOG_PURGED = 'AUDIT_LOG_PURGED',
  AUDIT_LOG_ANONYMIZED = 'AUDIT_LOG_ANONYMIZED',
  AUDIT_ALERT_CREATED = 'AUDIT_ALERT_CREATED',
  AUDIT_ALERT_UPDATED = 'AUDIT_ALERT_UPDATED',
  AUDIT_ALERT_DELETED = 'AUDIT_ALERT_DELETED',

  // NOTIFICATION ADMIN
  NOTIFICATION_BROADCAST_CREATED = 'NOTIFICATION_BROADCAST_CREATED',
  NOTIFICATION_BROADCAST_SENT = 'NOTIFICATION_BROADCAST_SENT',
  NOTIFICATION_BROADCAST_CANCELLED = 'NOTIFICATION_BROADCAST_CANCELLED',
  NOTIFICATION_TEMPLATE_CREATED = 'NOTIFICATION_TEMPLATE_CREATED',
  NOTIFICATION_TEMPLATE_UPDATED = 'NOTIFICATION_TEMPLATE_UPDATED',
  NOTIFICATION_DELIVERIES_RETRIED = 'NOTIFICATION_DELIVERIES_RETRIED',
  NOTIFICATION_USER_DATA_EXPORTED = 'NOTIFICATION_USER_DATA_EXPORTED',
  NOTIFICATION_USER_DATA_ERASED = 'NOTIFICATION_USER_DATA_ERASED',

  // SECURITY
  SECURITY_ALERT = 'SECURITY_ALERT',
}