export enum NotificationEventEnum {
  REPORT_RECEIVED = 'REPORT_RECEIVED',
  REPORT_UPDATED = 'REPORT_UPDATED',
  MORE_INFORMATION_REQUESTED = 'MORE_INFORMATION_REQUESTED',
  INFORMATION_REQUEST_RESPONDED = 'INFORMATION_REQUEST_RESPONDED',
  REPORT_ASSIGNED = 'REPORT_ASSIGNED',

  POST_APPROVED = 'POST_APPROVED',
  POST_REJECTED = 'POST_REJECTED',
  POST_CHANGES_REQUESTED = 'POST_CHANGES_REQUESTED',
  POST_UNPUBLISHED = 'POST_UNPUBLISHED',

  MISSING_PERSON_UPDATED = 'MISSING_PERSON_UPDATED',
  MISSING_PERSON_APPROVED = 'MISSING_PERSON_APPROVED',
  MISSING_PERSON_REJECTED = 'MISSING_PERSON_REJECTED',
  MISSING_PERSON_MORE_INFORMATION_REQUESTED = 'MISSING_PERSON_MORE_INFORMATION_REQUESTED',
  MISSING_PERSON_FOUND = 'MISSING_PERSON_FOUND',

  NEW_MISSING_PERSON_INFORMATION = 'NEW_MISSING_PERSON_INFORMATION',
  INFORMATION_SUBMISSION_REVIEWED = 'INFORMATION_SUBMISSION_REVIEWED',
  INFORMATION_SUBMISSION_REJECTED = 'INFORMATION_SUBMISSION_REJECTED',

  // NEW — used by SupportService.create() at creation time (status
  // PENDING). Previously create() fired SUPPORT_PAYMENT_CONFIRMED-
  // shaped payloads immediately, which misleadingly told the
  // supporter their payment was confirmed before any admin had
  // verified the off-platform transfer. SUPPORT_PAYMENT_CONFIRMED
  // below is now reserved solely for the CONFIRMED transition in
  // SupportService.updateStatus().
  SUPPORT_PLEDGE_CREATED = 'SUPPORT_PLEDGE_CREATED',
  SUPPORT_PAYMENT_CONFIRMED = 'SUPPORT_PAYMENT_CONFIRMED',

  NEW_REPORT = 'NEW_REPORT',
  HIGH_PRIORITY_REPORT = 'HIGH_PRIORITY_REPORT',
  NEW_POST = 'NEW_POST',
  NEW_MISSING_PERSON_REQUEST = 'NEW_MISSING_PERSON_REQUEST',

  SECURITY_ALERT = 'SECURITY_ALERT',

  // VICTIM PROFILE
  VICTIM_PROFILE_CREATED = 'VICTIM_PROFILE_CREATED',
  VICTIM_PROFILE_UPDATED = 'VICTIM_PROFILE_UPDATED',
  VICTIM_PROFILE_DELETED = 'VICTIM_PROFILE_DELETED',
  VICTIM_PROFILE_GATES_UPDATED = 'VICTIM_PROFILE_GATES_UPDATED',
  VICTIM_PROFILE_CHILD_SAFETY_REVIEWED = 'VICTIM_PROFILE_CHILD_SAFETY_REVIEWED',
  VICTIM_PROFILE_CONSENT_REVOKED = 'VICTIM_PROFILE_CONSENT_REVOKED',
  VICTIM_PROFILE_BANK_DETAILS_UPDATED = 'VICTIM_PROFILE_BANK_DETAILS_UPDATED',
  VICTIM_PROFILE_PUBLISHED = 'VICTIM_PROFILE_PUBLISHED',
  VICTIM_PROFILE_UNPUBLISHED = 'VICTIM_PROFILE_UNPUBLISHED',
  VICTIM_PROFILE_REJECTED = 'VICTIM_PROFILE_REJECTED',
  VICTIM_PROFILE_RESUBMITTED = 'VICTIM_PROFILE_RESUBMITTED',

  // AUTH
  PASSWORD_CHANGED = 'notification.password_changed',
  PASSWORD_RESET = 'notification.password_reset',
}