export enum PermissionsEnum {
  // Reports
  REPORT_READ = 'REPORT_READ',
  REPORT_REVIEW = 'REPORT_REVIEW',
  REPORT_UPDATE_STATUS = 'REPORT_UPDATE_STATUS',
  REPORT_REQUEST_INFO = 'REPORT_REQUEST_INFO',
  REPORT_ASSIGN = 'REPORT_ASSIGN',
  REPORT_ESCALATE = 'REPORT_ESCALATE',
  REPORT_CLOSE = 'REPORT_CLOSE',
  REPORT_EVIDENCE_READ = 'REPORT_EVIDENCE_READ',
  REPORTER_INFO_READ = 'REPORTER_INFO_READ',

  // Posts
  POST_READ = 'POST_READ',
  POST_REVIEW = 'POST_REVIEW',
  POST_APPROVE = 'POST_APPROVE',
  POST_REJECT = 'POST_REJECT',
  POST_REQUEST_CHANGES = 'POST_REQUEST_CHANGES',
  POST_PUBLISH = 'POST_PUBLISH',
  POST_UNPUBLISH = 'POST_UNPUBLISH',
  POST_CREATE_OFFICIAL = 'POST_CREATE_OFFICIAL',
  POST_DELETE = 'POST_DELETE',

  // Missing Persons
  MISSING_PERSON_READ = 'MISSING_PERSON_READ',
  MISSING_PERSON_REVIEW = 'MISSING_PERSON_REVIEW',
  MISSING_PERSON_APPROVE = 'MISSING_PERSON_APPROVE',
  MISSING_PERSON_REJECT = 'MISSING_PERSON_REJECT',
  MISSING_PERSON_UPDATE = 'MISSING_PERSON_UPDATE',
  MISSING_PERSON_INFO_READ = 'MISSING_PERSON_INFO_READ',
  MISSING_PERSON_INFO_REVIEW = 'MISSING_PERSON_INFO_REVIEW',
  MISSING_PERSON_PUBLISH = 'MISSING_PERSON_PUBLISH',
  MISSING_PERSON_UNPUBLISH = 'MISSING_PERSON_UNPUBLISH',
  MISSING_PERSON_DELETE = 'MISSING_PERSON_DELETE',
  MISSING_PERSON_REDACT = 'MISSING_PERSON_REDACT',

  // Victim Profiles
  PROFILE_READ = 'PROFILE_READ',
  PROFILE_CREATE = 'PROFILE_CREATE',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  PROFILE_REVIEW = 'PROFILE_REVIEW',
  PROFILE_APPROVE = 'PROFILE_APPROVE',
  PROFILE_PUBLISH = 'PROFILE_PUBLISH',
  PROFILE_UNPUBLISH = 'PROFILE_UNPUBLISH',
  PROFILE_DELETE = 'PROFILE_DELETE',
  PROFILE_CHILD_SAFETY_REVIEW = 'PROFILE_CHILD_SAFETY_REVIEW',
  PROFILE_BANK_DETAILS_MANAGE = 'PROFILE_BANK_DETAILS_MANAGE',
  PROFILE_CONSENT_MANAGE = 'PROFILE_CONSENT_MANAGE',

  // Support
  SUPPORT_READ = 'SUPPORT_READ',
  SUPPORT_REVIEW = 'SUPPORT_REVIEW',
  SUPPORT_PAYMENT_READ = 'SUPPORT_PAYMENT_READ',
  SUPPORT_PAYMENT_MANAGE = 'SUPPORT_PAYMENT_MANAGE',

  // Users
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_SUSPEND = 'USER_SUSPEND',
  USER_RESTORE = 'USER_RESTORE',
  USER_DELETE = 'USER_DELETE',
  USER_FORCE_LOGOUT = 'USER_FORCE_LOGOUT',
  USER_UNLOCK = 'USER_UNLOCK',
  USER_ROLE_ASSIGN = 'USER_ROLE_ASSIGN',
  USER_PROMOTE = 'USER_PROMOTE',

  // Roles
  ROLE_READ = 'ROLE_READ',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  // Permissions
  PERMISSION_READ = 'PERMISSION_READ',
  PERMISSION_ASSIGN = 'PERMISSION_ASSIGN',
  PERMISSION_REVOKE = 'PERMISSION_REVOKE',
  PERMISSION_MANAGE = 'PERMISSION_MANAGE',

  // Audit Logs
  AUDIT_LOG_READ = 'AUDIT_LOG_READ',
  AUDIT_LOG_READ_SENSITIVE = 'AUDIT_LOG_READ_SENSITIVE',
  AUDIT_LOG_EXPORT = 'AUDIT_LOG_EXPORT',
  AUDIT_LOG_PURGE = 'AUDIT_LOG_PURGE',
  AUDIT_LOG_ANONYMIZE = 'AUDIT_LOG_ANONYMIZE',
  AUDIT_LOG_VERIFY_INTEGRITY = 'AUDIT_LOG_VERIFY_INTEGRITY',
  AUDIT_ALERT_MANAGE = 'AUDIT_ALERT_MANAGE',

  // Notifications
  NOTIFICATION_READ = 'NOTIFICATION_READ',
  NOTIFICATION_MANAGE = 'NOTIFICATION_MANAGE',
  // NEW — gates NOTIFICATION_BROADCAST_SENT specifically. Creating/cancelling
  // a broadcast draft stays under NOTIFICATION_MANAGE; dispatching it to
  // (potentially) every user is a bigger blast radius and gets its own grant.
  NOTIFICATION_BROADCAST_SEND = 'NOTIFICATION_BROADCAST_SEND',
  // NEW — gates NOTIFICATION_USER_DATA_EXPORTED.
  NOTIFICATION_USER_DATA_EXPORT = 'NOTIFICATION_USER_DATA_EXPORT',
  // NEW — gates NOTIFICATION_USER_DATA_ERASED. GDPR-style erasure, previously
  // indistinguishable from generic NOTIFICATION_MANAGE.
  NOTIFICATION_USER_DATA_ERASE = 'NOTIFICATION_USER_DATA_ERASE',

  // Security Settings
  SECURITY_SETTINGS_READ = 'SECURITY_SETTINGS_READ',
  SECURITY_SETTINGS_UPDATE = 'SECURITY_SETTINGS_UPDATE',

  // Dashboard
  DASHBOARD_READ = 'DASHBOARD_READ',

  // Media
  MEDIA_UPLOAD = 'MEDIA_UPLOAD',
  MEDIA_DELETE = 'MEDIA_DELETE',
}